puts "Clearing database"
Review.destroy_all
Order.destroy_all
UserService.destroy_all
Service.destroy_all
Event.destroy_all
Bid.destroy_all
User.destroy_all
puts "Cleared"
puts "Seeding...."

chef = Service.create!(name: "Chef")
mixologist = Service.create!(name: "Mixologist")
waiter = Service.create!(name: "Waiter")

test1 = User.create!(first_name: "test", last_name:"test", email:"test@test.com", password:"test123", professional: true, bio:"Experienced Chef")
john = User.create!(first_name: "John", last_name:"Doe", email:"johndoe@gmail.com", password:"password", professional: true, bio:"Experienced Chef")
andrew = User.create!(first_name: "Andrew", last_name:"Smith", email:"andrewsmith@gmail.com", password:"password", professional: true, bio:"Looking for chef")

UserService.create!(service: chef , user: test1)
UserService.create!(service: waiter , user: john)
UserService.create!(service: mixologist , user: andrew)

event1 = Event.create!(name:"Birthday Party", date:"2018/12/18", event_type: "birthday", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 3, service: chef, min_price: 30, max_price: 50, user_id: andrew.id)
event2 =  Event.create!(name:"Leaving Do", date:"2019/03/29", event_type: "work party", location:"Manchester", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 10, service: chef, min_price: 10, max_price: 20, user_id: andrew.id)
event3 =  Event.create!(name:"Casual Dinner", date:"2018/12/19", event_type: "dinner", location:"Liverpool", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 10, service: waiter, min_price: 100, max_price: 150, user_id: andrew.id)
event4 =  Event.create!(name:"House Warming", date:"2018/12/19", event_type: "house party", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 10, service: chef, min_price: 50, max_price: 70, user_id: test1.id)
event5 =  Event.create!(name:"Dinner with Friends", date:"2018/12/19", event_type: "dinner", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 10, service: mixologist, min_price: 80, max_price: 110, user_id: andrew.id)
event6 =  Event.create!(name:"Cocktail Night", date:"2018/12/19", event_type: "cocktail party", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 10, service: mixologist, min_price: 1000, max_price: 1500, user_id: andrew.id)
event7 =  Event.create!(name:"Birthday Dinner", date:"2018/12/19", event_type: "birthday", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 10, service: chef, min_price: 1, max_price: 5, user_id: andrew.id)
event8 =  Event.create!(name:"Hen weekend", date:"2018/12/19", event_type: "hen", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 10, service: chef, min_price: 1, max_price: 5, user_id: test1.id)
event9 =  Event.create!(name:"Stag night", date:"2018/12/19", event_type: "stag", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 9, service: chef, min_price: 1, max_price: 5, user_id: andrew.id)
event10 =  Event.create!(name:"Divorce party", date:"2018/12/29", event_type: "party", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 17, service: chef, min_price: 1, max_price: 5, user_id: andrew.id)
event12 =  Event.create!(name:"Reunion Dinner", date:"2018/12/05", event_type: "Dinner", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 10, service: chef, min_price: 1, max_price: 5, user_id: test1.id)
event13 =  Event.create!(name:"30th Birthday!", date:"2018/12/19", event_type: "birthday", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 13, service: mixologist, min_price: 1, max_price: 5, user_id: andrew.id)
event14 =  Event.create!(name:"Fred's Farewell", date:"2018/12/17", event_type: "family event", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 10, service: chef, min_price: 1, max_price: 5, user_id: andrew.id)
event15 =  Event.create!(name:"Welcome Home party", date:"2018/12/10", event_type: "family event", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 20, service: chef, min_price: 1, max_price: 5, user_id: test1.id)
event16 =  Event.create!(name:"Fashion blogger Event", date:"2018/12/05", event_type: "business event", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 60, service: chef, min_price: 1, max_price: 5, user_id: test1.id)
event17 =  Event.create!(name:"Lipstick Launch party", date:"2018/12/01", event_type: "launch party", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 40, service: chef, min_price: 1, max_price: 5, user_id: andrew.id)
event18 =  Event.create!(name:"Botox Party", date:"2018/12/20", event_type: "party", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 16, service: chef, min_price: 1, max_price: 5, user_id: test1.id)
event19 =  Event.create!(name:"New Years Party", date:"2018/12/31", event_type: "new years", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 50, service: mixologist, min_price: 1, max_price: 5, user_id: andrew.id)
event20 =  Event.create!(name:"Engagement Party", date:"2018/09/01", event_type: "Engagement", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 50, service: mixologist, min_price: 1, max_price: 5, user_id: john.id)
event21 =  Event.create!(name:"Baby shower", date:"2018/11/17", event_type: "summer", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 50, service: waiter, min_price: 1, max_price: 5, user_id: test1.id)
event22 =  Event.create!(name:"Summer Party", date:"2018/08/17", event_type: "tea party", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 50, service: chef, min_price: 1, max_price: 5, user_id: andrew.id)
event23 =  Event.create!(name:"Tea party", date:"2018/07/08", event_type: "tea party", location:"London", description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus porta convallis erat, in placerat eros mattis id. Cras lectus sem, mollis sed libero nec, sagittis facilisis purus. Etiam tempus aliquam nisi ut accumsan. Quisque dictum varius magna a posuere. Suspendisse ullamcorper justo orci, sit amet suscipit ligula malesuada eu. Praesent in lorem sed odio tempor pretium eu sit amet justo", party_size: 50, service: mixologist, min_price: 1, max_price: 5, user_id: andrew.id)




bid1 = Bid.create!(quote: 200, description: "This bid is for birthday event 5 people" , status: "accepted", sku: chef.name, user_id: andrew.id, event_id: event1.id, price_cents: 100)
bid2 = Bid.create!(quote: 500, description: "This bid is for wedding event 50 people" , status: "accepted", sku: chef.name, user_id: john.id, event_id: event2.id, price_cents: 100)
bid3 = Bid.create!(quote: 1000, description: "This bid is for hen party event 10 people" ,status: "accepted", sku: waiter.name, user_id: andrew.id, event_id: event3.id, price_cents: 100)
bid4 = Bid.create!(quote: 500, description: "This bid is for whatever event 10 people" , sku: mixologist.name, user_id: john.id, event_id: event4.id, price_cents: 100)
bid5 = Bid.create!(quote: 1000, description: "This bid is for whatever 2 event 10 people" , sku: mixologist.name, user_id: andrew.id, event_id: event10.id, price_cents: 100)
bid6 = Bid.create!(quote: 600, description: "This bid is for birthday event 5 people" , status: "accepted", sku: chef.name, user_id: john.id, event_id: event22.id, price_cents: 100)
bid7 = Bid.create!(quote: 850, description: "This bid is for birthday event 5 people" , status: "accepted", sku: chef.name, user_id: john.id, event_id: event23.id, price_cents: 100)
bid8 = Bid.create!(quote: 1000, description: "This bid is for whatever 2 event 10 people" , status: "declined", sku: mixologist.name, user_id: john.id, event_id: event19.id, price_cents: 100)
bid9 = Bid.create!(quote: 250, description: "This bid is for wedding event 50 people" , status: "accepted", sku: chef.name, user_id: john.id, event_id: event18.id, price_cents: 100)
bid10 = Bid.create!(quote: 930, description: "This bid is for wedding event 50 people" , status: "declined", sku: chef.name, user_id: andrew.id, event_id: event16.id, price_cents: 100)
bid11 = Bid.create!(quote: 650, description: "This bid is for wedding event 50 people" , status: "accepted", sku: chef.name, user_id: john.id, event_id: event16.id, price_cents: 100)



puts "Seeded"

